version: "3.8"

# Set up the spring boot app service

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/kcb
      - DB_USERNAME=kcb
      - DB_PASSWORD=kcb
      - JWT_SECRET=secret

      # Set up the mysql database service
  mysql-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kcb
      - MYSQL_USER=kcb
      - MYSQL_PASSWORD=kcb
    volumes:
      - mysql-db-data:/var/lib/mysql

volumes:
    mysql-db-data: